# Generated by Django 4.1.7 on 2023-03-20 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DialogEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.TextField()),
                ('parenthetical', models.TextField(blank=True, null=True)),
                ('dialog', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SceneHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext_int', models.BooleanField()),
                ('place_name', models.TextField()),
                ('time_of_day', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransitionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transition', models.TextField()),
            ],
        ),
    ]
